### ISSUE TITLE
[PE-D] CS/CU module can add letter-grade

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-1/tp#229]
![Screenshot 2021-10-29 at 5.00.31 PM.png](https://raw.githubusercontent.com/siyuancheng178/ped/main/files/4f95af51-15a2-48f2-8591-98392f34c853.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: siyuancheng178/ped#1

**Comment by NonRNP** [comment]
We did not validate the grading basis for each module within this feature as the data isn't publicly available in the NUSMods api. Nevertheless, this feature is still able to achieve its main functionality as intended, that is to calculate the theoretical CAP of the user given the grade letter and the module credit (which is extracted from the module code), but not validating whether or not the grade letter is in compliance with each module's grading basis. This grade validation feature can be implemented in the future releases of the project, but it is now considered out of the project's scope for the current iteration.
