### ISSUE TITLE
[PE-D] cap has no link to module taken

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-1/tp#233]
![image.png](https://raw.githubusercontent.com/conradwee/ped/main/files/89fed74e-c415-47c4-a213-8472884fe1aa.png)

cap has no link to modules taken

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: conradwee/ped#4

**Comment by NonRNP** [comment]
The "cap code" and "cap mc" are used to calculate cap regardless of the modules taken. In order to calculate cap from the stored modules, the user must use "module cap" command instead.
