### ISSUE TITLE
[PE-D] inaccurate bus route

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-1/tp#259]
![Screenshot 2021-10-29 at 5.44.14 PM.png](https://raw.githubusercontent.com/ngoivanessa/ped/master/files/dcbbdc78-bb68-4ea6-b801-dc8ca1613b70.png)

there is a single change route that ug mentioned it is able to recommend

utown -> opp uhall (d2)
opp uhall -> com2 (a2)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ngoivanessa/ped#9

**Comment by shyamgj1900** [comment]
The problem occured because UTOWN itself was an interchange bus stop, hence BFS thinks that UTOWN is not connected to UTOWN and this caused the error. The problem has now been resolved.
